# Generated by Django 2.1.5 on 2019-02-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_vehicle_info',
            field=models.CharField(blank=True, help_text='special vehicle information', max_length=1000, null=True),
        ),
    ]
